version: "3.5"

services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    networks:
      - default
      - multi-region-sqs-base
  sqs:
    platform: linux/amd64
    image: roribio16/alpine-sqs
    ports:
      - "19324:9324"
      - "19325:9325"
networks:
  multi-region-sqs-base:
    name: multi-region-sqs-base
